apiVersion: v1
kind: ConfigMap
metadata:
  name: lzu-covid-report-delays
data:
  delays: ""

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: lzu-auto-covid-health-report
spec:
  schedule: "0 23 * 1,2,7,8 *"  # Schedule on CST 7 everyday during Jan. Feb. Jul. Aug.
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: lzu-auto-covid-health-report
            image: hollowman6/lzu-auto-covid-health-report:latest
            env:
              - name: DELAYS
                valueFrom:
                  configMapKeyRef:
                    name: lzu-covid-report-delays
                    key: delays
              - name: CARDID
                valueFrom:
                  secretKeyRef:
                    name: lzu-covid-report-secret
                    key: cardid
              - name: PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: lzu-covid-report-secret
                    key: password
              - name: SERVERCHANSCKEY
                valueFrom:
                  secretKeyRef:
                    name: lzu-covid-report-secret
                    key: serverchansckey
              - name: OPENID
                valueFrom:
                  secretKeyRef:
                    name: lzu-covid-report-secret
                    key: openid
              - name: PPTOKEN
                valueFrom:
                  secretKeyRef:
                    name: lzu-covid-report-secret
                    key: openid
              - name: PPTOPIC
                valueFrom:
                  secretKeyRef:
                    name: lzu-covid-report-secret
                    key: pptopic
          restartPolicy: OnFailure
