apiVersion: v2
name: lzu-auto-covid-health-report
description: A chart for deploying LZU Auto COVID Health Report. (兰大疫情期间自动定时健康打卡)
version: 1.0.9
type: application
appVersion: "1.0.9"
keywords:
  - lzu
home: "https://hollowman.ml/"
sources:
  - "https://github.com/HollowMan6/LZU-Auto-COVID-Health-Report"
maintainers:
  - name: Hollow Man
    email: hollowman@hollowman.ml
