name: 'Docker Version - GitHub Actions LZU Auto COVID Health Report'
    
on:
  workflow_dispatch:  # Allow manual triggers
    inputs:
      delays:
        description: 'Delayed time (Optional) 可选延迟时间'
        required: false
# schedule:
#   - cron: '0 23 * 1,2,7,8 *' # Schedule on CST 7 everyday during Jan. Feb. Jul. Aug.

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
        - name: Star original repository
          run: |
            curl \
            -X PUT \
            -H 'authorization: ${{ github.actor }} ${{ secrets.GITHUB_TOKEN }}' \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/user/starred/HollowMan6/LZU-Auto-COVID-Health-Report
        - name: Auto COVID Health Report
          uses: HollowMan6/LZU-Auto-COVID-Health-Report@main
          with:
            CARDID: ${{ secrets.CARDID }}
            PASSWORD: ${{ secrets.PASSWORD }}
            DELAYS: ${{ github.event.inputs.delays }}
            SERVERCHANSCKEY: ${{ secrets.SERVERCHANSCKEY }}
            OPENID: ${{ secrets.OPENID }}
            PPTOKEN: ${{ secrets.PPTOKEN }}
            PPTOPIC: ${{ secrets.PPTOPIC }}
            TGBOTTOKEN: ${{ secrets.TGBOTTOKEN }}
            TGCHATID: ${{ secrets.TGCHATID }}
        - name: 'Re-run workflow if failed and GPATOKEN set'
          env:
            GPATOKEN: ${{ secrets.GPATOKEN }}
          if: ${{ failure() && (env.GPATOKEN != '') }}
          uses: benc-uk/workflow-dispatch@v1
          with:
            workflow: 'Docker Version - GitHub Actions LZU Auto COVID Health Report'
            token: ${{ secrets.GPATOKEN }}
            inputs: '{ "delays": "30m" }'
